### ISSUE TITLE
[Bug] `conf_mask.pt` seems missing

### ISSUE THREAD

**Issue by wutongshenqiu** [njuaplusplus/mirror#1]
Hi, the `conf_mask.pt` file seems missing, is there any way to get it?

https://github.com/njuaplusplus/mirror/blob/17da0b72b80a3f18ce60d630b0e6cb60c9c17b2c/my_utils.py#L232

**Comment by njuaplusplus** [comment]
Hi, thank you for pointing out this. I have updated the code. Please use `python my_download_cache.py` to download it.

**Comment by wutongshenqiu** [comment]
Thanks!
